name: "PR: Validate Contract"

on: 
  - pull_request

jobs:
  
  with-mock:
    name: Validate requests (mocked)
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm i -g newman
      - name: Deploy Mock and Proxy
        run: make start-mockedproxy
      - name: Run contract validation
        run: make test
